services:
  rasa:
    image: rasa/rasa:latest
    ports:
      - "5005:5005"
    volumes:
      - .:/app
    command: ["run", "-m", "models", "--enable-api", "--cors", "*", "--debug"]
    environment:
      - ACTION_ENDPOINT=http://host.docker.internal:5055/webhook
      - SQLALCHEMY_SILENCE_UBER_WARNING=1

  action_server:
    build:
      context: .
      dockerfile: ./actions/Dockerfile
    image: rasa/rasa-sdk:latest
    ports:
      - "5055:5055"
    volumes:
      - ./actions:/app/actions
      - ./actions/dataset:/app/dataset
      - ./models:/app/models
      - ./endpoints.yml:/app/endpoints.yml 
    command: ["start", "--actions", "actions"]
