services:
  rasa:
    image: rasa/rasa:latest
    ports:
      - "5006:5005"
    volumes:
      - ./:/app
    command: ["run", "-m", "models", "--enable-api", "--cors", "*", "--debug"]

  action_server:
    image: rasa/rasa-sdk:latest
    volumes:
      - ./actions:/app/actions
    ports:
      - "5055:5055"
    command: ["run", "actions"]
